### ISSUE TITLE
Script Does Nothing

### ISSUE THREAD

**Issue by peterjschroeder** [rowanthorpe/build-jack-fox#1]
Running the script does nothing, no output is shown. I tried adding parameters which also shows/does nothing.

**Comment by rowanthorpe** [comment]
Hi, thanks for reporting in. This is just a plain shell-script without much user-friendly/diagnostics/logging code yet (other than usage info if you run `./build-jack-fox --help`), and for now it primarily relies on `set -e` to exit non-zero on errors. For now the best bet (for you - to know what's wrong, and for me - to find out if it is script-error, documentation-error, user-error, or incompatible system) is to run it as `sh -x ./build-jack-fox` (instead of the normal `./build-jack-fox`), and to work out where and why it stopped based on the trailing lines of output. If you are familiar with shellscripts and Debian-based systems you can probably work it out yourself from that - in which case please let me know what it was in the end, otherwise if it looks too confusing please copy-paste the output here *but first do censor out any personally identifiable information you don't want publicly displayed* before sending it. The things you might want to censor are e.g. homedir-pathnames, username, possible $DEBEMAIL or $DEBFULLNAME if you have them already configured, and anything you might have already hand-edited in the `build-jack-fox-conf.sh` config-file.

**Comment by peterjschroeder** [comment]
Thank you. It was the DEBEMAIL line. I had to manually set it to my email. After that I had to manually create /usr/local/src/build-jack-fox

**Comment by rowanthorpe** [comment]
Glad you got it working. I have left the die-and-warn for the missing directory because for now I prefer the least invasive approach, and as the warning clarifies that the directory is missing I think that makes it easy enough to manually create it - as you just did.

As for the other issue, I can't see how it was failing for you on the "DEBEMAIL line" (I guess you mean line 66?) because I have protected the invocation of the potentially missing command (`getent`, inside `get_user_email()`) so that it just outputs empty without failing, and then if empty in the end it replaces it with `blah@example.com`. Can you please re-run it in debug mode without manually setting the email address and let me know where exactly it fails (i.e what command, what line number)?

**Comment by peterjschroeder** [comment]
Running with -x and not setting the email address shows this.

+ set -e
+ basename build-jack-fox
+ scriptname=build-jack-fox
+ printf %s\n build-jack-fox
+ sed -e s/./ /g
+ scriptnspc=              
+ jack_dev_pkg_candidates=libjack-jackd2-dev libjack-dev
+ srcdir_def=/usr/local/src/build-jack-fox
+ local_version_suffix_def=local1
+ local_version_suffix_regex_def=local[0-9]\+
+ jack_dev_pkg_def=libjack-jackd2-dev
+ get_user_full_name
+ + cut -d, -f1
id -run
+ cut -d: -f5
+ getent passwd *****
+ name_def=*****
+ name_def=*****
+ get_user_email
+ id -run
+ grep @
+ sed -e s/^[^ \t]\+:[ \t]\+//
+ getent aliases *****
+ :
+ email_def=

**Comment by rowanthorpe** [comment]
Ah! Thanks for that - I found where the bug is. I forgot that when grep has no input it returns `1` which borks the `set -e`, so when the `getent aliases` finds nothing the `grep '@'` errors the script. I will fix that now (which will auto-close this issue), and once the fix is in you won't need to manually set the email address as a workaround.
