### ISSUE TITLE
Failing on Ubuntu 18.10

### ISSUE THREAD

**Issue by windowsrefund** [rowanthorpe/build-jack-fox#2]
Hello,

Just an FYI that this is failing on Ubuntu 18.10 with the following:

```
Get:1 http://us.archive.ubuntu.com/ubuntu cosmic-updates/main firefox 64.0+build3-0ubuntu0.18.10.1 (diff) [250 kB]
Fetched 250 kB in 0s (1,203 kB/s)
Download complete and in download only mode
sed: can't read firefox_64.0.dsc: No such file or directory
sed: can't read firefox_64.0.dsc: No such file or directory

```

I did make progress by hacking up the script a bit but am so far down the rabbit hole at this point that I figured I'd just post the original error. Even with my changes, I'm still unable to compile anyway.

At some point, I changed direction and did the following:

```
sudo apt-get build-dep firefox
apt-get source firefox
cd firefox-*
```
Added `ac_add_options --enable-jack` to debian/config/mozconfig.in

```
dpkg-buildpackage -b -us -uc

```
but after about 30 minutes...

```
*** KEEP ALIVE MARKER ***
Total duration: 0:34:00.894319
34:38.55 {standard input}: Assembler messages:
34:38.56 {standard input}:337397: Warning: end of file not at end of a line; newline inserted
34:38.56 {standard input}:338697: Error: unknown pseudo-op: `.lbb39262'
```

**Comment by rowanthorpe** [comment]
Hi, many thanks for the bug report, and really sorry for only seeing it now - I haven't had the chance for much open-source stuff lately, and also didn't see the notification email. Unfortunately I don't have time to investigate this deeply, but at a glance it looks like a combination of things, probably including some old-fashioned bitrot. That is because for the last few Firefox versions I've just reverted to using the distro's version since they re-added plain Alsa output (which means it works without Pulse and Jack, with the main gotcha being that it doesn't handle multiple audio streams at once, but I effectively never need that these days anyway). I will leave this open for a while in case someone feels courageous enough to tackle it. I doubt I will get the time to, and may not even have time to review anything if they do (but if that ends up being the case, someone might feel motivated to fork their own repo and maintain that instead...).

**Comment by rowanthorpe** [comment]
I am archiving this repo because I am moving to self-hosting code. The repo will be available at the new location I will indicate in the repo's "about" text in a few minutes, but for the reasons mentioned in the previous comment, and to not leave a dangling open issue here I am closing this (sorry, I wish I had time to actually address this issue, but life got in the way, and then I ended up using the Alsa workaround instead of this code).
